INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (5, ' Alexander Azabache Gutierrez', '997 589 380', 'a.azabache@ccicsa.com.mx - Jefe de proyectos Zona Sur', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (6, 'Luis Herrera Marquina', '989 595 220', 'l.herreram@condumex.com.mx - Coordinador de manttos preventivos', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (7, 'Carlos Aurelio Caceres Maquera', '987 579 056', 'c.caceresm@ccicsa.com.mx - Coordinador de manttos correctivos', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (8, ' Hosmer Castillo De La Cruz', '914 684 618', 'h.castillo@ccicsa.com.mx', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (9, 'Adrian  Rodriguez Huarca', '943 510 024', 'a.rodrigue25@ccicsa.com.mx - Lider de zona', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (10, 'Jairo Misme Baca', '987 591 664', 'j.mismebaca@ccicsa.com.mx - Lider de zona', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (11, 'Manuel Gabriel Raa Caceres', '993 362 183', 'm.raacaceres@ccicsa.com.mx - Supervidor de HD', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (12, ' Karyn Monroy Corzo', '914 088 229', 'k.monroy@ccicsa.com.mx', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (13, 'Danitza Cruz Cabrera', '987 632 004', 'd.cruzcabrer@ccicsa.com.mx - Ingeniero de seguridadd', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (14, 'Elvis Enmerson Vilca Chicata', '986 673 932', 'e.vilcachica@ccicsa.com.mx', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (15, 'Lorena Katerine Joaquin Iparraguirre', '989 066 808', 'l.joaquin@ccicsa.com.mx', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (16, 'Valeria Mercedes Siccha Mendieta', '967 765 412', 'v.siccha@ccicsa.com.mx', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (17, ' Miriam Brigite Pariona Felipa', '989210069', 'm.pariona@ccicsa.com.mx - Control de Materiales', 1);
INSERT INTO customers_contacts (id, name, phone, additional_information, customer_id) VALUES (18, 'Wendy Piñas Santiago', '987641252', 'wpinas@condumex.com.mx - Control de Proyecto y Liquidaciones', 1);
