// Esto permite Tree-shaking
export { default as AcceptIcon } from './AcceptIcon.vue';
export { default as DeleteIcon } from './DeleteIcon.vue';
export { default as DisableIcon } from './DisableIcon.vue';
export { default as DocumentsIcon } from './DocumentsIcon.vue';
export { default as DocumentIcon } from './DocumentIcon.vue';
export { default as PlusDocumentIcon } from './PlusDocumentIcon.vue';
export { default as DownArrowIcon } from './DownArrowIcon.vue';
export { default as DownloadIcon } from './DownloadIcon.vue';
export { default as EditIcon } from './EditIcon.vue';
export { default as ExcelIcon } from './ExcelIcon.vue';
export { default as GroupIcon } from './GroupIcon.vue';
export { default as ImagesIcon } from './ImagesIcon.vue';
export { default as InformationIcon } from './InformationIcon.vue';
export { default as LinkIcon } from './LinkIcon.vue';
export { default as ListIcon } from './ListIcon.vue';
// export { default as MenuIcon } from './MenuIcon.vue';
export { default as PlusCircleIcon } from './PlusCircleIcon.vue';
export { default as RechargeIcon } from './RechargeIcon.vue';
export { default as RejectIcon } from './RejectIcon.vue';
export { default as ServerIcon } from './ServerIcon.vue';
export { default as ShowIcon } from './ShowIcon.vue';
export { default as SortDateIcon } from './SortDateIcon.vue';
export { default as SortIcon } from './SortIcon.vue';
export { default as SuscribeIcon } from './SuscribeIcon.vue';
export { default as UnsubscribeIcon } from './UnsubscribeIcon.vue';
export { default as UpArrowIcon } from './UpArrowIcon.vue';
export { default as UploadIcon } from './UploadIcon.vue';
export { default as LlaveIcon } from './LlaveIcon.vue';
export { default as ToolIcon } from './ToolIcon.vue';
export { default as SecurityIcon } from './SecurityIcon.vue';
export { default as VehicleIcon } from './VehicleIcon.vue';

export { default as DolarIcon } from './DolarIcon.vue';
export { default as EyeOutlineIcon } from './EyeOutlineIcon.vue';
export { default as EyeSlashSolidIcon } from './EyeSlashSolidIcon.vue';

export { default as CalendarIcon } from './CalendarIcon.vue';
export { default as FolderIcon } from './FolderIcon.vue';
export { default as PlayIcon } from './PlayIcon.vue';
export { default as PauseIcon } from './PauseIcon.vue';
export { default as AddUserIcon } from './AddUserIcon.vue';
export { default as RectangleGroupIcon } from './RectangleGroupIcon.vue';
